language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'

dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

services:
  - mysql
  - postgresql

before_script:
  - mysql -u root -e "create database IF NOT EXISTS test;"
  - mysql -u root test < examples/sql/mysql.sql -u root
  - psql -c 'create database test;' -U postgres
  - psql -d test -a -f examples/sql/pgsql.sql
  - sqlite3 examples/test.sqlite < examples/sql/sqlite.sql

install:
- composer install

script:
  - vendor/bin/phpunit -c ./phpunit.xml