language: php

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

dist: trusty

addons:
  apt:
    packages:
      - mysql-server
      - mysql-client-core
      - mysql-client
    services:
      - mysql
      - postgresql

before_script:
  - if [[ $TRAVIS_PHP_VERSION = hhvm ]]; then mysql  -e 'create database test;'; fi
  - if [[ $TRAVIS_PHP_VERSION = hhvm ]]; then mysql test < examples/example-database.sql; fi

script:
  - phpunit -c ./tests/phpunit.xml